### ISSUE TITLE
release 未签名 ipa

### ISSUE THREAD

**Issue by Silent-wqh** [luoxuhai/Alock#1]
可以 release 一个未签名的 ipa 吗？手里没有 mac 没法打包

**Comment by luoxuhai** [comment]
晚上下班后可以试试 🥲

**Comment by luoxuhai** [comment]
> 可以 release 一个未签名的 ipa 吗？手里没有 mac 没法打包

ipa 已上传：https://github.com/luoxuhai/Alock/releases/tag/v1.0.1
