### ISSUE TITLE
你可以直接支持在爱思里面下载安装吗？

### ISSUE THREAD

**Issue by good-ideal** [luoxuhai/Alock#2]
如题

**Comment by long2ice** [comment]
我这边提示安装包验证失败

**Comment by good-ideal** [comment]
![image](https://user-images.githubusercontent.com/41094378/226501870-18254dc1-4942-48d0-8f54-72feebe869af.png)
安装失败

**Comment by luoxuhai** [comment]
我这边可以安装，我晚上下班后再看看😂

**Comment by HailPHP** [comment]
![image](https://user-images.githubusercontent.com/22851730/227399155-88a9bf5e-c761-47da-ad45-e27189021f55.png)
我也是的

**Comment by HailPHP** [comment]
> 

要先用爱思助手签名工具，我选择appid登录签名就可以安装了
目前卡在屏幕使用时间授权上

**Comment by f497196689** [comment]
安装失败，提示 【无法安装此APP,因为无法验证其完整性。】

**Comment by AcquireKnown** [comment]
> > 
> 
> 要先用爱思助手签名工具，我选择appid登录签名就可以安装了 目前卡在屏幕使用时间授权上

这样是不是每一周都要重新弄一次才行
