### ISSUE TITLE
用爱思安装，提示安装包验证失败，怎么搞？IOS16.3.1

### ISSUE THREAD

**Issue by dddreams** [luoxuhai/Alock#5]

**Comment by VincentCheungCW** [comment]
需要先签名，安装签名后的ipa。

**Comment by dhicoc** [comment]
如何获取屏幕使用时间权限

**Comment by Sunny-boop** [comment]
爱思签名提示ipa包压缩失败咋办

**Comment by dddreams** [comment]
> 需要先签名，安装签名后的ipa。

**Comment by dddreams** [comment]
> 需要先签名，安装签名后的ipa。

有没有教程什么的，小白表示不会

**Comment by AcquireKnown** [comment]
求助，爱思助手安装失败，提示安装包验证失败或者设备未越狱。

**Comment by nikleechan** [comment]
我签名安装后，点 授予屏幕访问时间权限 没有反应。重启手机试过，自签试过，企业证书签名也尝试过，都是一样。iPhone13，ios 16.1.2。
